### ISSUE TITLE
Buildings lost Road connection but Grid is the same as before

### ISSUE THREAD

**Issue by chameleon-tbn** [kianzarrin/NodeController#2]
As soon as i reach corner smoothness of 53 Buildings directly at the corner may lose their road connection.

![image](https://user-images.githubusercontent.com/37211016/81296447-364e6400-9072-11ea-8539-cb9d3deb7797.png)

![image](https://user-images.githubusercontent.com/37211016/81296380-14ed7800-9072-11ea-8b21-c43d3579894a.png)

The Grid stays the same as with an unmanipulated node.

1. Why the Building loses the road connection if the grid is the same?
2. Would it not be better to manipulate also the grid to fit with the new corner smoothing?

Over all the traffic seems to flow very smooth on normal junctions.

**Comment by kianzarrin** [comment]
That is the problem with the base game. This is what happens when I change corner offset from asset editor.

![Screenshot (1040)](https://user-images.githubusercontent.com/26344691/81311694-6277de00-908e-11ea-9f55-afe06713210a.png)

Fixing zoning problems of the base game is well out of the scope of this mod. Maybe it can be handled in a complementary mod. I have in my mind ideas for a mod that can bend zones like SimCity.

**Comment by chameleon-tbn** [comment]
Thank you for explanation!
