### ISSUE TITLE
Feature Request: Move stop line

### ISSUE THREAD

**Issue by s2500111** [kianzarrin/NodeController#24]
I don't know, if it is possible, but one of the (sometimes unwanted) side effects of increasing the corner offset of intersections is, that it also moves the point where vehicles stop. Which is fine on certain intersections and not so good on others.

So it would be nice to have an influence on that point and move it forward. See image, the red line marks the point where vehicles wait. It would be nicer if this point could be moved closer to the dashed line while maintaining the corner offset.
![20201216092129_1](https://user-images.githubusercontent.com/11500068/102322929-1c69ed80-3f80-11eb-81b8-ca98edd80855.jpg)

**Comment by kianzarrin** [comment]
you cannot move the stop lines forward with node controller.
moving stop lines have a functional aspect and a visual aspect.
IMT already takes care of the visual part.
taking care of the functional part would require fixing Path finding which would be a TMPE issue.
alternatively, juniper is developing a mod called lane controller (or pathmanager extended or whatever it is called). So that can be used to bring the lanes forward I guess.

@s2500111 in the image above you can solve the issue by pressing enter blocked junction. so that would be a workaround.

I will close this issue because nothing can be done in the node controller.
