### ISSUE TITLE
Fine tune in bend mode

### ISSUE THREAD

**Issue by Sipke82** [kianzarrin/NodeController#5]
Would be nice if we could fine tune in bend mode so that the lines could match perfectly:

![image](https://user-images.githubusercontent.com/30873812/81580442-bd227a00-93ad-11ea-9ca1-7e36fabb65c1.png)

**Comment by kianzarrin** [comment]
@Sipke82 Just use the stretch mode. 

Bend mode matches linearly but stretch mode stretches the texture so that it matches better.

EDIT: Bend mode is mainly useful at asym roads or road corners (or maybe near ground to elevated segment?)

I am thinking maybe I should turn bend mode off if stretch is available because so far stretch has always been better than bend for me. But I am going to keep it in to give more freedom. maybe other people have found a use for it and I am unaware off.

**Comment by kianzarrin** [comment]
There is also this:
https://github.com/kianzarrin/AutomaticNodePainter/issues/1
